#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <winreg.h>
#include <time.h>
#include <tchar.h>
#include <string.h>
#include <strsafe.h>
#include <fcntl.h>
#include <io.h>
#include <stdio.h>
